version: 0.2

env:
  variables:
    PRODROOT: "$pwd/ecomap"
    PYSRCROOT: "${PRODROOT}/src/python"

  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    commands:
      - yum install -y python2-pip
      - yum install -y python-devel  
      - yum install -y httpd
      - yum install -y mod_wsgi
      - yum install -y mysql-devel
      - yum install -y MySQL-python
      - yum install -y memcached
      - yum install -y libxslt-devel
      - yum install -y libxml2-devel
      - pip install --upgrade setuptools
      - pip install --upgrade pip
  pre_build:
    commands:
      - cd ecomap && pip2 install -r requirements.txt
      - pip install pycodestyle
      
  build:
    commands:
      - pycodestyle -v src/*.py
      - echo "pycodestyle found no issues!"
      - python -m pytest
  post_build:
    commands:
      - echo "All test passed"
#artifacts:
  #files:
    # - We don't currently preserve any artifacts
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - We don't currently cache anything
