version: 0.2



  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    commands:
      - yum install -y python2-pip
      - yum install -y python-devel  
      - yum install -y httpd
      - yum install -y mod_wsgi
      - yum install -y mysql-devel
      - yum install -y MySQL-python
      - yum install -y memcached
      - yum install -y libxslt-devel
      - yum install -y libxml2-devel
      - pip install --upgrade setuptools
      - pip install --upgrade pip
  pre_build:
    commands:
      - cd ecomap && pip2 install --user -r requirements.txt
      
  build:
    commands:
      - PRODROOT=$pwd/ecomap
      - PYSRCROOT=${PRODROOT}/src/python
      - CONFROOT=${PRODROOT}/etc
      - PYTHONPATH=$PYSRCROOT
      - PYTHON=${PYTHON:-/etc/python}
      - STATICROOT=${STATICROOT:-${PRODROOT}/www/}
      - PYTHON_EGG_CACHE=${PYTHON_EGG_CACHE:-/tmp/.python-eggs}
      - export PRODROOT PYSRCROOT PYTHONPATH CONFROOT STATICROOT PYTHON_EGG_CACHE
      - echo "$PRODROOT"
    #  - python2 -m unittest discover -s ${PRODROOT}/unittest/src/python/ecomap 
      
  post_build:
    commands:
      - echo "test passed"
artifacts:
  files:
    - ecopmap/*
  discard-paths: yes
  name: python-eco-$(date +%Y-%m-%d-%H-%M-%S).zip
