version: 0.2

#env:
  #variables:
     # key: "There are no variables"
  #parameter-store:
     # key: "There are no variables"

phases:
  install:
    commands:
      - yum install -y apache2
      - yum install -y git
      - yum install -y libapache2-mod-wsgi  
      - yum install -y libffi-dev
      - yum install -y libmysqlclient-dev
      - yum install -y libssl-dev
      - yum install -y libxml2-dev
      - yum install -y libxslt1-dev
      - yum install -y memcached
      - yum install -y mysql-client
      - yum install -y python-dev
      - yum install -y python-pip
      - pip install --upgrade pip
  pre_build:
    commands:
      
      - pip install -r requirements.txt
      
  build:
    commands:
      - pytest tests/unit/
      - pytest tests/integration/ -rfs
  post_build:
    commands:
      - python setup.py sdist bdist_wheel
#artifacts:
  #files:
    # - We don't currently preserve any artifacts
  #name: $(date +%Y-%m-%d)
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - We don't currently cache anything
